/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['en', 'fr'])
export const enum_projects_project_contents_image_groups_images_ratio = pgEnum(
  'enum_projects_project_contents_image_groups_images_ratio',
  ['4-3', '16-10', '16-9', '21-9', '5-1'],
)
export const enum_projects_project_contents_image_groups_display = pgEnum(
  'enum_projects_project_contents_image_groups_display',
  ['columns', 'rows', 'grid'],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    'sizes_4/3_url': varchar('sizes_4_3_url'),
    'sizes_4/3_width': numeric('sizes_4_3_width', { mode: 'number' }),
    'sizes_4/3_height': numeric('sizes_4_3_height', { mode: 'number' }),
    'sizes_4/3_mimeType': varchar('sizes_4_3_mime_type'),
    'sizes_4/3_filesize': numeric('sizes_4_3_filesize', { mode: 'number' }),
    'sizes_4/3_filename': varchar('sizes_4_3_filename'),
    'sizes_16/10_url': varchar('sizes_16_10_url'),
    'sizes_16/10_width': numeric('sizes_16_10_width', { mode: 'number' }),
    'sizes_16/10_height': numeric('sizes_16_10_height', { mode: 'number' }),
    'sizes_16/10_mimeType': varchar('sizes_16_10_mime_type'),
    'sizes_16/10_filesize': numeric('sizes_16_10_filesize', { mode: 'number' }),
    'sizes_16/10_filename': varchar('sizes_16_10_filename'),
    'sizes_16/9_url': varchar('sizes_16_9_url'),
    'sizes_16/9_width': numeric('sizes_16_9_width', { mode: 'number' }),
    'sizes_16/9_height': numeric('sizes_16_9_height', { mode: 'number' }),
    'sizes_16/9_mimeType': varchar('sizes_16_9_mime_type'),
    'sizes_16/9_filesize': numeric('sizes_16_9_filesize', { mode: 'number' }),
    'sizes_16/9_filename': varchar('sizes_16_9_filename'),
    'sizes_21/09_url': varchar('sizes_21_09_url'),
    'sizes_21/09_width': numeric('sizes_21_09_width', { mode: 'number' }),
    'sizes_21/09_height': numeric('sizes_21_09_height', { mode: 'number' }),
    'sizes_21/09_mimeType': varchar('sizes_21_09_mime_type'),
    'sizes_21/09_filesize': numeric('sizes_21_09_filesize', { mode: 'number' }),
    'sizes_21/09_filename': varchar('sizes_21_09_filename'),
    'sizes_5/1_url': varchar('sizes_5_1_url'),
    'sizes_5/1_width': numeric('sizes_5_1_width', { mode: 'number' }),
    'sizes_5/1_height': numeric('sizes_5_1_height', { mode: 'number' }),
    'sizes_5/1_mimeType': varchar('sizes_5_1_mime_type'),
    'sizes_5/1_filesize': numeric('sizes_5_1_filesize', { mode: 'number' }),
    'sizes_5/1_filename': varchar('sizes_5_1_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_4_3_sizes_4_3_filename_idx').on(columns['sizes_4/3_filename']),
    index('media_sizes_16_10_sizes_16_10_filename_idx').on(columns['sizes_16/10_filename']),
    index('media_sizes_16_9_sizes_16_9_filename_idx').on(columns['sizes_16/9_filename']),
    index('media_sizes_21_09_sizes_21_09_filename_idx').on(columns['sizes_21/09_filename']),
    index('media_sizes_5_1_sizes_5_1_filename_idx').on(columns['sizes_5/1_filename']),
  ],
)

export const collaborators = pgTable(
  'collaborators',
  {
    id: serial('id').primaryKey(),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    displayName: varchar('display_name'),
    folioOwner: boolean('folio_owner'),
    firstName: varchar('first_name').notNull(),
    lastName: varchar('last_name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('collaborators_avatar_idx').on(columns.avatar),
    index('collaborators_updated_at_idx').on(columns.updatedAt),
    index('collaborators_created_at_idx').on(columns.createdAt),
  ],
)

export const projects_collaborators = pgTable(
  'projects_collaborators',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    collaborator: integer('collaborator_id').references(() => collaborators.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('projects_collaborators_order_idx').on(columns._order),
    index('projects_collaborators_parent_id_idx').on(columns._parentID),
    index('projects_collaborators_collaborator_idx').on(columns.collaborator),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [projects.id],
      name: 'projects_collaborators_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const projects_project_contents_image_groups_images = pgTable(
  'projects_project_contents_image_groups_images',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    ratio: enum_projects_project_contents_image_groups_images_ratio('ratio')
      .notNull()
      .default('4-3'),
  },
  (columns) => [
    index('projects_project_contents_image_groups_images_order_idx').on(columns._order),
    index('projects_project_contents_image_groups_images_parent_id_idx').on(columns._parentID),
    index('projects_project_contents_image_groups_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [projects_project_contents_image_groups.id],
      name: 'projects_project_contents_image_groups_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const projects_project_contents_image_groups = pgTable(
  'projects_project_contents_image_groups',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    display: enum_projects_project_contents_image_groups_display('display')
      .notNull()
      .default('columns'),
  },
  (columns) => [
    index('projects_project_contents_image_groups_order_idx').on(columns._order),
    index('projects_project_contents_image_groups_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [projects_project_contents.id],
      name: 'projects_project_contents_image_groups_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const projects_project_contents = pgTable(
  'projects_project_contents',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    description: jsonb('description'),
  },
  (columns) => [
    index('projects_project_contents_order_idx').on(columns._order),
    index('projects_project_contents_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [projects.id],
      name: 'projects_project_contents_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const projects = pgTable(
  'projects',
  {
    id: serial('id').primaryKey(),
    archive: boolean('archive').notNull().default(false),
    cover: integer('cover_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    projectUrl: varchar('project_url'),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle').notNull(),
    description: varchar('description').notNull(),
    clientName: varchar('client_name'),
    clientUrl: varchar('client_url'),
    projectType: integer('project_type_id').references(() => project_types.id, {
      onDelete: 'set null',
    }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('projects_cover_idx').on(columns.cover),
    index('projects_project_type_idx').on(columns.projectType),
    index('projects_updated_at_idx').on(columns.updatedAt),
    index('projects_created_at_idx').on(columns.createdAt),
  ],
)

export const projects_rels = pgTable(
  'projects_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    skillsID: integer('skills_id'),
    rolesID: integer('roles_id'),
  },
  (columns) => [
    index('projects_rels_order_idx').on(columns.order),
    index('projects_rels_parent_idx').on(columns.parent),
    index('projects_rels_path_idx').on(columns.path),
    index('projects_rels_skills_id_idx').on(columns.skillsID),
    index('projects_rels_roles_id_idx').on(columns.rolesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [projects.id],
      name: 'projects_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['skillsID']],
      foreignColumns: [skills.id],
      name: 'projects_rels_skills_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['rolesID']],
      foreignColumns: [roles.id],
      name: 'projects_rels_roles_fk',
    }).onDelete('cascade'),
  ],
)

export const roles = pgTable(
  'roles',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('roles_updated_at_idx').on(columns.updatedAt),
    index('roles_created_at_idx').on(columns.createdAt),
  ],
)

export const project_types = pgTable(
  'project_types',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('project_types_updated_at_idx').on(columns.updatedAt),
    index('project_types_created_at_idx').on(columns.createdAt),
  ],
)

export const skills = pgTable(
  'skills',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    description: varchar('description').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('skills_updated_at_idx').on(columns.updatedAt),
    index('skills_created_at_idx').on(columns.createdAt),
  ],
)

export const skills_rels = pgTable(
  'skills_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('skills_rels_order_idx').on(columns.order),
    index('skills_rels_parent_idx').on(columns.parent),
    index('skills_rels_path_idx').on(columns.path),
    index('skills_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [skills.id],
      name: 'skills_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'skills_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const activities_blocks_medias_page_medias = pgTable(
  'activities_blocks_medias_page_medias',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }),
    folder: varchar('folder'),
  },
  (columns) => [
    index('activities_blocks_medias_page_medias_order_idx').on(columns._order),
    index('activities_blocks_medias_page_medias_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [activities_blocks_medias_page.id],
      name: 'activities_blocks_medias_page_medias_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const activities_blocks_medias_page = pgTable(
  'activities_blocks_medias_page',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('activities_blocks_medias_page_order_idx').on(columns._order),
    index('activities_blocks_medias_page_parent_id_idx').on(columns._parentID),
    index('activities_blocks_medias_page_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [activities.id],
      name: 'activities_blocks_medias_page_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const activities_blocks_music_page_showcase_playlists = pgTable(
  'activities_blocks_music_page_showcase_playlists',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    playlistUrl: varchar('playlist_url').notNull(),
  },
  (columns) => [
    index('activities_blocks_music_page_showcase_playlists_order_idx').on(columns._order),
    index('activities_blocks_music_page_showcase_playlists_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [activities_blocks_music_page.id],
      name: 'activities_blocks_music_page_showcase_playlists_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const activities_blocks_music_page = pgTable(
  'activities_blocks_music_page',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    approxMinutesPerYear: numeric('approx_minutes_per_year', { mode: 'number' }).notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('activities_blocks_music_page_order_idx').on(columns._order),
    index('activities_blocks_music_page_parent_id_idx').on(columns._parentID),
    index('activities_blocks_music_page_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [activities.id],
      name: 'activities_blocks_music_page_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const activities = pgTable(
  'activities',
  {
    id: serial('id').primaryKey(),
    cover: integer('cover_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    description: varchar('description').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('activities_cover_idx').on(columns.cover),
    index('activities_updated_at_idx').on(columns.updatedAt),
    index('activities_created_at_idx').on(columns.createdAt),
  ],
)

export const activities_rels = pgTable(
  'activities_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('activities_rels_order_idx').on(columns.order),
    index('activities_rels_parent_idx').on(columns.parent),
    index('activities_rels_path_idx').on(columns.path),
    index('activities_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [activities.id],
      name: 'activities_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'activities_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    collaboratorsID: integer('collaborators_id'),
    projectsID: integer('projects_id'),
    rolesID: integer('roles_id'),
    projectTypesID: integer('project_types_id'),
    skillsID: integer('skills_id'),
    activitiesID: integer('activities_id'),
    'payload-kvID': integer('payload_kv_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_collaborators_id_idx').on(columns.collaboratorsID),
    index('payload_locked_documents_rels_projects_id_idx').on(columns.projectsID),
    index('payload_locked_documents_rels_roles_id_idx').on(columns.rolesID),
    index('payload_locked_documents_rels_project_types_id_idx').on(columns.projectTypesID),
    index('payload_locked_documents_rels_skills_id_idx').on(columns.skillsID),
    index('payload_locked_documents_rels_activities_id_idx').on(columns.activitiesID),
    index('payload_locked_documents_rels_payload_kv_id_idx').on(columns['payload-kvID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['collaboratorsID']],
      foreignColumns: [collaborators.id],
      name: 'payload_locked_documents_rels_collaborators_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['rolesID']],
      foreignColumns: [roles.id],
      name: 'payload_locked_documents_rels_roles_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectTypesID']],
      foreignColumns: [project_types.id],
      name: 'payload_locked_documents_rels_project_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['skillsID']],
      foreignColumns: [skills.id],
      name: 'payload_locked_documents_rels_skills_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['activitiesID']],
      foreignColumns: [activities.id],
      name: 'payload_locked_documents_rels_activities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-kvID']],
      foreignColumns: [payload_kv.id],
      name: 'payload_locked_documents_rels_payload_kv_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const about_page_header_socials = pgTable(
  'about_page_header_socials',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('about_page_header_socials_order_idx').on(columns._order),
    index('about_page_header_socials_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_header_socials_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_other_experiences = pgTable(
  'about_page_other_experiences',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    company: varchar('company').notNull(),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('about_page_other_experiences_order_idx').on(columns._order),
    index('about_page_other_experiences_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_other_experiences_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_other_education = pgTable(
  'about_page_other_education',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    major: varchar('major').notNull(),
    school: varchar('school').notNull(),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
  },
  (columns) => [
    index('about_page_other_education_order_idx').on(columns._order),
    index('about_page_other_education_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_other_education_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page_other_awwards = pgTable(
  'about_page_other_awwards',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    project: integer('project_id')
      .notNull()
      .references(() => projects.id, {
        onDelete: 'set null',
      }),
    awwarder: varchar('awwarder').notNull(),
    mention: varchar('mention').notNull(),
  },
  (columns) => [
    index('about_page_other_awwards_order_idx').on(columns._order),
    index('about_page_other_awwards_parent_id_idx').on(columns._parentID),
    index('about_page_other_awwards_project_idx').on(columns.project),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [about_page.id],
      name: 'about_page_other_awwards_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const about_page = pgTable(
  'about_page',
  {
    id: serial('id').primaryKey(),
    Loader_firstName: varchar('loader_first_name').notNull(),
    Loader_lastName: varchar('loader_last_name').notNull(),
    Header_sidePhoto: integer('header_side_photo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    Header_title: varchar('header_title').notNull(),
    Header_location: varchar('header_location').notNull(),
    Header_description: varchar('header_description').notNull(),
    Header_resumee: integer('header_resumee_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('about_page_header_header_side_photo_idx').on(columns.Header_sidePhoto),
    index('about_page_header_header_resumee_idx').on(columns.Header_resumee),
  ],
)

export const about_page_rels = pgTable(
  'about_page_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
    activitiesID: integer('activities_id'),
    skillsID: integer('skills_id'),
  },
  (columns) => [
    index('about_page_rels_order_idx').on(columns.order),
    index('about_page_rels_parent_idx').on(columns.parent),
    index('about_page_rels_path_idx').on(columns.path),
    index('about_page_rels_media_id_idx').on(columns.mediaID),
    index('about_page_rels_activities_id_idx').on(columns.activitiesID),
    index('about_page_rels_skills_id_idx').on(columns.skillsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [about_page.id],
      name: 'about_page_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'about_page_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['activitiesID']],
      foreignColumns: [activities.id],
      name: 'about_page_rels_activities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['skillsID']],
      foreignColumns: [skills.id],
      name: 'about_page_rels_skills_fk',
    }).onDelete('cascade'),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_collaborators = relations(collaborators, ({ one }) => ({
  avatar: one(media, {
    fields: [collaborators.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
}))
export const relations_projects_collaborators = relations(projects_collaborators, ({ one }) => ({
  _parentID: one(projects, {
    fields: [projects_collaborators._parentID],
    references: [projects.id],
    relationName: 'collaborators',
  }),
  collaborator: one(collaborators, {
    fields: [projects_collaborators.collaborator],
    references: [collaborators.id],
    relationName: 'collaborator',
  }),
}))
export const relations_projects_project_contents_image_groups_images = relations(
  projects_project_contents_image_groups_images,
  ({ one }) => ({
    _parentID: one(projects_project_contents_image_groups, {
      fields: [projects_project_contents_image_groups_images._parentID],
      references: [projects_project_contents_image_groups.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [projects_project_contents_image_groups_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_projects_project_contents_image_groups = relations(
  projects_project_contents_image_groups,
  ({ one, many }) => ({
    _parentID: one(projects_project_contents, {
      fields: [projects_project_contents_image_groups._parentID],
      references: [projects_project_contents.id],
      relationName: 'imageGroups',
    }),
    images: many(projects_project_contents_image_groups_images, {
      relationName: 'images',
    }),
  }),
)
export const relations_projects_project_contents = relations(
  projects_project_contents,
  ({ one, many }) => ({
    _parentID: one(projects, {
      fields: [projects_project_contents._parentID],
      references: [projects.id],
      relationName: 'projectContents',
    }),
    imageGroups: many(projects_project_contents_image_groups, {
      relationName: 'imageGroups',
    }),
  }),
)
export const relations_projects_rels = relations(projects_rels, ({ one }) => ({
  parent: one(projects, {
    fields: [projects_rels.parent],
    references: [projects.id],
    relationName: '_rels',
  }),
  skillsID: one(skills, {
    fields: [projects_rels.skillsID],
    references: [skills.id],
    relationName: 'skills',
  }),
  rolesID: one(roles, {
    fields: [projects_rels.rolesID],
    references: [roles.id],
    relationName: 'roles',
  }),
}))
export const relations_projects = relations(projects, ({ one, many }) => ({
  cover: one(media, {
    fields: [projects.cover],
    references: [media.id],
    relationName: 'cover',
  }),
  projectType: one(project_types, {
    fields: [projects.projectType],
    references: [project_types.id],
    relationName: 'projectType',
  }),
  collaborators: many(projects_collaborators, {
    relationName: 'collaborators',
  }),
  projectContents: many(projects_project_contents, {
    relationName: 'projectContents',
  }),
  _rels: many(projects_rels, {
    relationName: '_rels',
  }),
}))
export const relations_roles = relations(roles, () => ({}))
export const relations_project_types = relations(project_types, () => ({}))
export const relations_skills_rels = relations(skills_rels, ({ one }) => ({
  parent: one(skills, {
    fields: [skills_rels.parent],
    references: [skills.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [skills_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_skills = relations(skills, ({ many }) => ({
  _rels: many(skills_rels, {
    relationName: '_rels',
  }),
}))
export const relations_activities_blocks_medias_page_medias = relations(
  activities_blocks_medias_page_medias,
  ({ one }) => ({
    _parentID: one(activities_blocks_medias_page, {
      fields: [activities_blocks_medias_page_medias._parentID],
      references: [activities_blocks_medias_page.id],
      relationName: 'medias',
    }),
  }),
)
export const relations_activities_blocks_medias_page = relations(
  activities_blocks_medias_page,
  ({ one, many }) => ({
    _parentID: one(activities, {
      fields: [activities_blocks_medias_page._parentID],
      references: [activities.id],
      relationName: '_blocks_mediasPage',
    }),
    medias: many(activities_blocks_medias_page_medias, {
      relationName: 'medias',
    }),
  }),
)
export const relations_activities_blocks_music_page_showcase_playlists = relations(
  activities_blocks_music_page_showcase_playlists,
  ({ one }) => ({
    _parentID: one(activities_blocks_music_page, {
      fields: [activities_blocks_music_page_showcase_playlists._parentID],
      references: [activities_blocks_music_page.id],
      relationName: 'showcasePlaylists',
    }),
  }),
)
export const relations_activities_blocks_music_page = relations(
  activities_blocks_music_page,
  ({ one, many }) => ({
    _parentID: one(activities, {
      fields: [activities_blocks_music_page._parentID],
      references: [activities.id],
      relationName: '_blocks_musicPage',
    }),
    showcasePlaylists: many(activities_blocks_music_page_showcase_playlists, {
      relationName: 'showcasePlaylists',
    }),
  }),
)
export const relations_activities_rels = relations(activities_rels, ({ one }) => ({
  parent: one(activities, {
    fields: [activities_rels.parent],
    references: [activities.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [activities_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_activities = relations(activities, ({ one, many }) => ({
  cover: one(media, {
    fields: [activities.cover],
    references: [media.id],
    relationName: 'cover',
  }),
  _blocks_mediasPage: many(activities_blocks_medias_page, {
    relationName: '_blocks_mediasPage',
  }),
  _blocks_musicPage: many(activities_blocks_music_page, {
    relationName: '_blocks_musicPage',
  }),
  _rels: many(activities_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    collaboratorsID: one(collaborators, {
      fields: [payload_locked_documents_rels.collaboratorsID],
      references: [collaborators.id],
      relationName: 'collaborators',
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects',
    }),
    rolesID: one(roles, {
      fields: [payload_locked_documents_rels.rolesID],
      references: [roles.id],
      relationName: 'roles',
    }),
    projectTypesID: one(project_types, {
      fields: [payload_locked_documents_rels.projectTypesID],
      references: [project_types.id],
      relationName: 'projectTypes',
    }),
    skillsID: one(skills, {
      fields: [payload_locked_documents_rels.skillsID],
      references: [skills.id],
      relationName: 'skills',
    }),
    activitiesID: one(activities, {
      fields: [payload_locked_documents_rels.activitiesID],
      references: [activities.id],
      relationName: 'activities',
    }),
    'payload-kvID': one(payload_kv, {
      fields: [payload_locked_documents_rels['payload-kvID']],
      references: [payload_kv.id],
      relationName: 'payload-kv',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_about_page_header_socials = relations(
  about_page_header_socials,
  ({ one }) => ({
    _parentID: one(about_page, {
      fields: [about_page_header_socials._parentID],
      references: [about_page.id],
      relationName: 'Header_socials',
    }),
  }),
)
export const relations_about_page_other_experiences = relations(
  about_page_other_experiences,
  ({ one }) => ({
    _parentID: one(about_page, {
      fields: [about_page_other_experiences._parentID],
      references: [about_page.id],
      relationName: 'Other_experiences',
    }),
  }),
)
export const relations_about_page_other_education = relations(
  about_page_other_education,
  ({ one }) => ({
    _parentID: one(about_page, {
      fields: [about_page_other_education._parentID],
      references: [about_page.id],
      relationName: 'Other_education',
    }),
  }),
)
export const relations_about_page_other_awwards = relations(
  about_page_other_awwards,
  ({ one }) => ({
    _parentID: one(about_page, {
      fields: [about_page_other_awwards._parentID],
      references: [about_page.id],
      relationName: 'Other_awwards',
    }),
    project: one(projects, {
      fields: [about_page_other_awwards.project],
      references: [projects.id],
      relationName: 'project',
    }),
  }),
)
export const relations_about_page_rels = relations(about_page_rels, ({ one }) => ({
  parent: one(about_page, {
    fields: [about_page_rels.parent],
    references: [about_page.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [about_page_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
  activitiesID: one(activities, {
    fields: [about_page_rels.activitiesID],
    references: [activities.id],
    relationName: 'activities',
  }),
  skillsID: one(skills, {
    fields: [about_page_rels.skillsID],
    references: [skills.id],
    relationName: 'skills',
  }),
}))
export const relations_about_page = relations(about_page, ({ one, many }) => ({
  Header_sidePhoto: one(media, {
    fields: [about_page.Header_sidePhoto],
    references: [media.id],
    relationName: 'Header_sidePhoto',
  }),
  Header_socials: many(about_page_header_socials, {
    relationName: 'Header_socials',
  }),
  Header_resumee: one(media, {
    fields: [about_page.Header_resumee],
    references: [media.id],
    relationName: 'Header_resumee',
  }),
  Other_experiences: many(about_page_other_experiences, {
    relationName: 'Other_experiences',
  }),
  Other_education: many(about_page_other_education, {
    relationName: 'Other_education',
  }),
  Other_awwards: many(about_page_other_awwards, {
    relationName: 'Other_awwards',
  }),
  _rels: many(about_page_rels, {
    relationName: '_rels',
  }),
}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_projects_project_contents_image_groups_images_ratio: typeof enum_projects_project_contents_image_groups_images_ratio
  enum_projects_project_contents_image_groups_display: typeof enum_projects_project_contents_image_groups_display
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  collaborators: typeof collaborators
  projects_collaborators: typeof projects_collaborators
  projects_project_contents_image_groups_images: typeof projects_project_contents_image_groups_images
  projects_project_contents_image_groups: typeof projects_project_contents_image_groups
  projects_project_contents: typeof projects_project_contents
  projects: typeof projects
  projects_rels: typeof projects_rels
  roles: typeof roles
  project_types: typeof project_types
  skills: typeof skills
  skills_rels: typeof skills_rels
  activities_blocks_medias_page_medias: typeof activities_blocks_medias_page_medias
  activities_blocks_medias_page: typeof activities_blocks_medias_page
  activities_blocks_music_page_showcase_playlists: typeof activities_blocks_music_page_showcase_playlists
  activities_blocks_music_page: typeof activities_blocks_music_page
  activities: typeof activities
  activities_rels: typeof activities_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  about_page_header_socials: typeof about_page_header_socials
  about_page_other_experiences: typeof about_page_other_experiences
  about_page_other_education: typeof about_page_other_education
  about_page_other_awwards: typeof about_page_other_awwards
  about_page: typeof about_page
  about_page_rels: typeof about_page_rels
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_collaborators: typeof relations_collaborators
  relations_projects_collaborators: typeof relations_projects_collaborators
  relations_projects_project_contents_image_groups_images: typeof relations_projects_project_contents_image_groups_images
  relations_projects_project_contents_image_groups: typeof relations_projects_project_contents_image_groups
  relations_projects_project_contents: typeof relations_projects_project_contents
  relations_projects_rels: typeof relations_projects_rels
  relations_projects: typeof relations_projects
  relations_roles: typeof relations_roles
  relations_project_types: typeof relations_project_types
  relations_skills_rels: typeof relations_skills_rels
  relations_skills: typeof relations_skills
  relations_activities_blocks_medias_page_medias: typeof relations_activities_blocks_medias_page_medias
  relations_activities_blocks_medias_page: typeof relations_activities_blocks_medias_page
  relations_activities_blocks_music_page_showcase_playlists: typeof relations_activities_blocks_music_page_showcase_playlists
  relations_activities_blocks_music_page: typeof relations_activities_blocks_music_page
  relations_activities_rels: typeof relations_activities_rels
  relations_activities: typeof relations_activities
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_about_page_header_socials: typeof relations_about_page_header_socials
  relations_about_page_other_experiences: typeof relations_about_page_other_experiences
  relations_about_page_other_education: typeof relations_about_page_other_education
  relations_about_page_other_awwards: typeof relations_about_page_other_awwards
  relations_about_page_rels: typeof relations_about_page_rels
  relations_about_page: typeof relations_about_page
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
